# Github pages configuration
title: cbElasticsearch
description: Elasticsearch integration module for the Coldbox CFML platform
logo: /_assets/images/coldbox-logo.png

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-cayman